AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sysco Mock APIs

Resources:

  Products:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/globalSettings.handler
      Runtime: nodejs6.10
      Events:
        GetGlobalSettingsById:
          Type: Api
          Properties:
            Path: /global-settings/{id}
            Method: get
        PostGlobalSettingsById:
          Type: Api
          Properties:
            Path: /global-settings/{id}
            Method: post
        PutGlobalSettingsById:
          Type: Api
          Properties:
            Path: /global-settings/{id}
            Method: put

  Looksup:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/looksup.handler
      Runtime: nodejs6.10
      Events:
        GetLooksupAll:
          Type: Api
          Properties:
            Path: /looksup
            Method: get
        GetLooksupByCategory:
          Type: Api
          Properties:
            Path: /looksup/{category}
            Method: get

  OpCos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/opCos.handler
      Runtime: nodejs6.10
      Events:
        GetOpCosAll:
          Type: Api
          Properties:
            Path: /opcos
            Method: get
        GetOpCosById:
          Type: Api
          Properties:
            Path: /opcos/{id}
            Method: get

  Users:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/users.handler
      Runtime: nodejs6.10
      Events:
        GetUsersAll:
          Type: Api
          Properties:
            Path: /users
            Method: get
        GetUsersById:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
        PostUsers:
          Type: Api
          Properties:
            Path: /users
            Method: post
        PutUsersById:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: put

  Groups:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/groups.handler
      Runtime: nodejs6.10
      Events:
        GetGroupsAll:
          Type: Api
          Properties:
            Path: /groups
            Method: get
        GetGroupsById:
          Type: Api
          Properties:
            Path: /groups/{id}
            Method: get
        PostGroups:
          Type: Api
          Properties:
            Path: /groups
            Method: post
        PutGroupsById:
          Type: Api
          Properties:
            Path: /groups/{id}
            Method: put

  Locations:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler/locations.handler
      Runtime: nodejs6.10
      Events:
        GetLocationsAll:
          Type: Api
          Properties:
            Path: /locations
            Method: get
        GetLocationsById:
          Type: Api
          Properties:
            Path: /locations/{id}
            Method: get
        PostLocations:
          Type: Api
          Properties:
            Path: /locations
            Method: post
        PutLocationsById:
          Type: Api
          Properties:
            Path: /locations/{id}
            Method: put
